shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#
#ShopBundle_ajax_delivery_select:
#  resource: "@ShopBundle/Controller/"
#  defaults: { _controller: ShopBundle:Ajax:UpdateDeliveryController }