services:
#    shop.example:
#        class: ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#    category.twig_extension:
#        class: ShopBundle\Twig\Extension\CategoryExtension
#        tags:
#            -{ name: twig.extension }
